<?php
/**
 * @file
 * Provides a fiware HTTP client implemented in Guzzle.
 *
 * @copyright Copyright(c) 2012 Previous Next Pty Ltd
 * @license GPL v2 http://www.fsf.org/licensing/licenses/gpl.html
 * @author Chris Skene chris at previousnext dot com dot au
 */


require '/home/ubuntu/immense/php-macaroons/vendor/autoload.php';
use Macaroons\Macaroon;
use Macaroons\Verifier;



function myapp_client_menu() {
	$items = array();  
$items['myapp-service'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'Connect with Fiware Orion Cntext Broker', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('myapp_client_form'), //put the name of the form here
    'access callback' => TRUE
  );


  $items['myapp-auth'] = array( //this creates a URL that will call this form at "examples/form-example"
    'title' => 'My App service', //page title
    'description' => 'A form to mess around with.',
    'page callback' => 'myapp_client_deserialize', 'myapp_client_final',// 'myapp_client_deserialize', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => '',//array('myapp_client_form'), // $tokenmyapp, //put the name of the form here
    'access callback' => TRUE
  );
  
return $items;

}


function myapp_client_createuser($iduser){

//This will generate a random password, you could set your own here
  $password = user_password(8);

  //set up the user fields
  $fields = array(
    'name' => $iduser,
    'mail' => $iduser . '@example.com',
    'pass' => $password,
    'status' => 1,
    'init' => 'email address',
    'roles' => array(
      DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    ),
  );

  //the first parameter is left blank so a new user is created
  $account = user_save('', $fields);

  // If you want to send the welcome email, use the following code

  // Manually set the password so it appears in the e-mail.
  $account->password = $fields['pass'];

  // Send the e-mail through the user module.
//  drupal_mail('user', 'register_no_approval_required', $email, NULL, array('account' => $account), variable_get('site_mail', 'noreply@example..com'));

return $account;

}


function myapp_client_deserialize(){
		$token =$_GET['token'];
		$location = 'location';
		$key = 'key';
	        $caveat = 'first_party';      
		$m1 = Macaroon::deserialize($token);
		$verifier = new Verifier();
		$verifier->satisfyExact($caveat);
		$verified = $verifier->verify($m1, $key);
		echo '</br>Location deser:' . $m1->getLocation() ."\n";
		echo '</br>Identifier deser:' . $m1->getIdentifier() ."\n";
		echo '</br>Signature deser:' . $m1->getSignature() ."\n";

		$id = $m1->getIdentifier();
		echo ($verified ? "True" : "False") . "\n";
		

		$user = user_load_by_name($id);
			if(!$user){
			    // User doesn't exist and create
				myapp_client_createuser($id);
				$user = user_load_by_name($id);
				$user_id = $user->uid;
				global $user;
				myapp_client_user_login($user_id);
			} 
			else {
			    // User exists
				global $user;
				$user = user_load_by_name($id);
		                $user_id = $user->uid;
		                myapp_client_user_login($user_id);
		}

return true;
}


function myapp_client_user_login($userid)
{
	$user = user_load($userid);
	drupal_session_regenerate($userid);
	drupal_goto("user/$userid");
return true;
}


function myapp_client_form($form, &$form_state) {

 $form['url'] = array(
    '#type' => 'textfield', //you can find a list of available types in the form api
    '#title' => 'Service url?',
    '#size' => 50,
    '#maxlength' => 150,
    '#required' => TRUE, //make this field required
  );

$form['start_tracking'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable tracking'),
    '#default_value' => isset($settings['start_tracking']) ? $settings['start_tracking'] : FALSE,
    '#description' => t('If checked, then the user tracking will start to send to orion context broker tracking data'),
  );
$form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit!'),
  );

  return $form;
}

function myapp_client_form_submit($form, &$form_state) {

  global $user;
  if ($user->uid ) {
    if(!empty($form_state['values']['url'])){
     generate_token($form_state['values']['url'],$user);
                // post_fiware($form_state['values']['url']);// get_fiware($form_state['values']['url']);
    }else {
     print "please set a service url";
     die("please set service url");
    }

  }else {
  // Not logged in
  //  print "Please go to login page";
   die("please login");
  }

}
//post to specified url

function post_fiware(&$url,&$userid,&$userip){
  $login_count="";  // number of times the user has logged-in;
  $join_date="";   //ime stamp representing when the user joined;
  $login_days="";  //login_days — number of days since the user was last logged-in to the site;
  $reg_days="";   // — number of days since the user registered on the site;
  $online="";     // — whether the user is online (basically whether they have done anything in the last 15 minutes);

$query = db_select('field_data_field_terms', 't');//field_data_field_terms
$query->condition('t.entity_id', $userid, '=');

$query->fields('t', array('field_terms_tid'));
$r = $query->execute();
$nm = "";
//$i = 0;
foreach($r as $result)
{
 $nm .= "," . get_term_exist_in_vocab($result->field_terms_tid);
 //i++;
}

//$userid= 4999;

}

//https://api.drupal.org/api/drupal/modules%21user%21user.module/7
//http://www.apaddedcell.com/an-introduction-user-stats-module-drupal
function track_login_users(&$url,&$user){

                // $users = entity_load('user');// $arrayuids = array_keys($users);
     if($user->uid){
      $uid=$user->uid;
      //call tracking function   //get_user_track($user->uid);
      // divide to time slices
      $ip = user_stats_get_stats('ip_address', $user->uid);
       post_fiware($url,$uid,$ip);  //call post fnc to orion context broker
     }//end if

   curl_close($ch);  // Close request to clear up some resources
	
 return;
}		
